server:
  port: 8989
  servlet:
    context-path: /springboot
    jsp:
      init-parameters:
        development: true
  tomcat:
    uri-encoding: UTF-8
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pro
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
mybatis:
  type-aliases-package: com.baizhi.entity              #mybatis中的别名设置
  mapper-locations: classpath:com/baizhi/mapper/*.xml  #?mapper中的位置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
